# ChatGLM-6B QLoRA微调配置文件

# 模型配置
model:
  name_or_path: "THUDM/chatglm-6b"
  cache_dir: null
  use_fast_tokenizer: true
  model_revision: "main"
  use_auth_token: false

# 数据配置
data:
  train_file: "data/train_triplet.jsonl"
  validation_file: "data/val_triplet.jsonl"
  max_source_length: 512
  max_target_length: 256
  ignore_pad_token_for_loss: true

# LoRA配置
lora:
  r: 8
  alpha: 32
  dropout: 0.1
  target_modules: ["query_key_value"]

# 训练配置
training:
  output_dir: "output/chatglm-6b-triplet-qlora"
  num_train_epochs: 3
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 4
  gradient_accumulation_steps: 4
  learning_rate: 2e-4
  warmup_steps: 100
  logging_steps: 10
  save_steps: 500
  eval_steps: 500
  evaluation_strategy: "steps"
  save_strategy: "steps"
  load_best_model_at_end: true
  metric_for_best_model: "eval_loss"
  greater_is_better: false
  fp16: true
  gradient_checkpointing: true
  dataloader_pin_memory: false

# 量化配置
quantization:
  load_in_4bit: true
  bnb_4bit_compute_dtype: "float16"
  bnb_4bit_use_double_quant: true
  bnb_4bit_quant_type: "nf4"